import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import App from './App';

test('terminal and email copy controls work', async () => {
  render(<App />);
  const input = screen.getByLabelText('terminal input');
  fireEvent.change(input, { target: { value: 'help' } });
  fireEvent.submit(input.closest('form'));
  expect(screen.getByText(/experience — list roles/)).toBeInTheDocument();
  expect(screen.queryByText(/or try the terminal/i)).not.toBeInTheDocument();
  expect(screen.getByText(/Try the terminal here/i)).toBeInTheDocument();
  expect(document.querySelectorAll('.project-image-wrap img')).toHaveLength(0);
  expect(document.querySelector('.project-feature img')).toHaveAttribute('src', '/images/flexright-screenshot.png');
  expect(document.querySelectorAll('.leadership-photos img')).toHaveLength(2);
  expect(document.querySelector('.hero-card-wrap .hero-portrait img')).toHaveAttribute('src', '/abby.jpeg');
  expect(document.querySelector('#about img')).toBeNull();
  expect(screen.getByText(/Studying Computer Engineering at the University of Florida/)).toBeInTheDocument();
  expect(screen.getByText('National Society of Black Engineers - Fall Regional Conference 2025!')).toBeInTheDocument();
  expect(screen.queryByText(/hello_world/i)).not.toBeInTheDocument();
  expect(screen.queryByText('👋')).not.toBeInTheDocument();
  expect(document.querySelector('.marquee-wrap')).toBeNull();
  const writeText = jest.fn().mockResolvedValue(undefined);
  Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText } });
  fireEvent.click(document.querySelector('.hero-actions button[aria-label="Copy email address"]'));
  await waitFor(() => expect(writeText).toHaveBeenCalledWith('abigailzhepburn@gmail.com'));
  expect(await screen.findByRole('status')).toHaveTextContent('Email copied to clipboard');
  expect(document.querySelector('a[href="https://github.com/abbyhepburn/Face-Detection"]')).toBeInTheDocument();
  expect(document.querySelectorAll('.project-card')[0].querySelectorAll('.project-tags .tag')).toHaveLength(5);
  expect(screen.getByText('Open to internships, oppurtuntities, and good conversations.')).toBeInTheDocument();
  expect(screen.queryByText(/designed & built from scratch/i)).not.toBeInTheDocument();
  fireEvent.change(input, { target: { value: 'experience' } });
  fireEvent.submit(input.closest('form'));
  expect(screen.getByText(/BeachLens — Data Engineer Intern/)).toBeInTheDocument();
  fireEvent.change(input, { target: { value: 'contact' } });
  fireEvent.submit(input.closest('form'));
  expect(screen.getAllByText(/abigailzhepburn@gmail.com/)[0]).toBeInTheDocument();
});
